import { docsLoader, i18nLoader } from '@astrojs/starlight/loaders';
import { docsSchema, i18nSchema } from '@astrojs/starlight/schema';
import { defineCollection } from 'astro:content';

export const collections = {
  // Generated by scripts/sync-content.mjs; see docs-src/.
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
  // Starlight always reads this collection. en.json restates one default label so it is not
  // empty, which would make every build warn.
  i18n: defineCollection({ loader: i18nLoader(), schema: i18nSchema() }),
};
